controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # ackermann_steering_controller:
    #   type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bot_controller :
      type: diff_drive_controller/DiffDriveController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

bot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ['base_back_left_wheel_joint','base_front_left_wheel_joint']
    right_wheel_names: ['base_back_right_wheel_joint','base_front_right_wheel_joint']

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.67
    wheel_radius: 0.175
    wheels_per_side: 2

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: base_footprint

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

# Ackermann Steering Controller Parameters
# ackermann_steering_controller:
#   ros__parameters:
#     # Vehicle geometry
#     wheelbase: 0.9
#     steering_track_width: 0.67
#     traction_track_width: 0.67
#     traction_wheels_radius: 0.175
    
#     # Joint names - steering joints
#     traction_joints_names: 
#               - base_back_right_wheel_joint
#               - base_back_left_wheel_joint
  
#     # Joint names - drive joints  
#     steering_joints_names: 
#             - base_front_right_steering_joint
#             - base_front_left_steering_joint

#     # Wheel parameters
#     wheel_radius: 0.175

#     # Odometry settings
#     odom_frame_id: odom
#     base_frame_id: base_footprint
#     pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
#     twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

#     # Enable/disable odom
#     open_loop: false
#     enable_odom_tf: true

#     # Velocity and acceleration limits
#     linear:
#       x:
#         has_velocity_limits: true
#         has_acceleration_limits: true
#         has_jerk_limits: false
#         max_velocity: 5.0
#         min_velocity: -5.0
#         max_acceleration: 2.5
#         min_acceleration: -2.5
#         max_jerk: 0.0
#         min_jerk: 0.0

#     angular:
#       z:
#         has_velocity_limits: true
#         has_acceleration_limits: true
#         has_jerk_limits: false
#         max_velocity: 2.0
#         min_velocity: -2.0
#         max_acceleration: 1.5
#         min_acceleration: -1.5
#         max_jerk: 0.0
#         min_jerk: 0.0

#     # Command timeout
#     cmd_vel_timeout: 0.5
#     # Publishing rate
#     publish_rate: 50.0

#     # Use stamped twist message
#     use_stamped_vel: false

#     # Position feedback for steering
#     position_feedback: true
    
#     # Reference timeout
#     reference_timeout: 1.0


# Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_front_left_steering_joint
      - base_front_right_steering_joint
      # - base_front_left_wheel_joint
      # - base_front_right_wheel_joint
      - base_back_left_wheel_joint
      - base_back_right_wheel_joint

forward_position_controller:
  ros__parameters:
    joints:
      - base_front_right_steering_joint
      - base_front_left_steering_joint
    interface_name: position


forward_velocity_controller:
  ros__parameters:
    joints:
      - base_back_right_wheel_joint
      - base_back_left_wheel_joint
    interface_name: velocity